# npm run build - pre build
# Temel bir Nginx imajı kullanarak çalıştırma aşaması
FROM nginx:alpine

# Çalışma dizinini ayarlayın
WORKDIR /usr/share/nginx/html

# Prebuild edilmiş dosyaları kopyalayın
COPY build/ .

# Nginx'i başlatın
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


##LABEL authors="tersoman"
#FROM node:20.12-alpine3.18 AS build_stage
#WORKDIR /app
#COPY package*.json ./
#RUN npm install
#COPY . .
#RUN npm run build
#
#FROM node:alpine
#WORKDIR /app
#COPY --from=build_stage /app/build .
#RUN npm install -g http-server
#EXPOSE 3000
#CMD ["http-server", "-p", "3000"]
#
## docker build --tag frontend/test/1 --file Dockerfile_frontend .