# Build aşaması
FROM node:20.12-alpine3.18 AS build_stage

# Çalışma dizinini ayarla
WORKDIR /app

# Bağımlılıkları yükle
COPY package*.json ./
RUN npm install

# Uygulama kaynak kodunu kopyala
COPY . .

# Build işlemini gerçekleştir
RUN npm run build

# Çalıştırma aşaması
FROM nginx:alpine

# Çalışma dizinini ayarla
WORKDIR /usr/share/nginx/html

# Build edilmiş dosyaları kopyala
COPY --from=build_stage /app/build .

# Nginx'i başlat
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
